version: "3.9"


x-project: &project
  build:
    context: .
    target: local
  env_file: .env
  stdin_open: true
  tty: true
  working_dir: /code
   
services:
  app:
    <<: *project
    command:
      uvicorn app.api.main:app --host 0.0.0.0 --reload 
    ports:
      - "8079:8000"
    volumes:
      - .:/code
  
  app-tests:
    <<: *project
    command:
      bash -c "python scripts/init_db.py -n testdb && alembic upgrade head && pytest && python scripts/drop_db.py testdb"
    env_file: .env.tests
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - .:/code
    
  db:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 3
    ports:
      - "5432:5432"
 
volumes:

  postgres-data: